# names.ini
# Location library format:
#   name = lat, lon[, alt]
#
# Edit from CLI:
#   ./bin/astro --name <name> --lat <lat> --lon <lon> [--alt <alt>]
# If name exists, astro asks for confirmation, comments the old line,
# and appends the new value.

ny_aalesund = 78.92423, 11.92082, 8.0
ny_aalesund_rabben_geodetic_observatory = 78.92927, 11.86777, 38.0
ny_aalesund_brandal_observatory = 78.94296, 11.85323, 4.0
